services:
    file_storage.transport.local_file:
        autowire: true
        autoconfigure: true
        public: true
        class: JorisRos\FileStorage\Transport\LocaleFile
        bind:
            $parameters: "test"

    file_storage.file_storage_service:
        autowire: true
        autoconfigure: true
        public: true
        class: JorisRos\FileStorage\FileStorageService
        arguments: ["@file_storage.transport.local_file"]
